name: tensorflow2
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cd-hit=4.6.8=hfc679d8_2
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - absl-py==2.3.1
    - anyio==4.12.0
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - asttokens==3.0.1
    - astunparse==1.6.3
    - async-lru==2.0.5
    - attrs==25.4.0
    - babel==2.17.0
    - beautifulsoup4==4.14.3
    - bleach==6.2.0
    - cachetools==6.2.2
    - certifi==2025.11.12
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - comm==0.2.3
    - contourpy==1.3.0
    - cycler==0.12.1
    - debugpy==1.8.17
    - decorator==5.2.1
    - defusedxml==0.7.1
    - dm-tree==0.1.8
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - filelock==3.19.1
    - flatbuffers==25.9.23
    - fonttools==4.60.1
    - fqdn==1.5.1
    - fsspec==2025.10.0
    - gast==0.7.0
    - google-auth==2.41.1
    - google-auth-oauthlib==1.2.3
    - google-pasta==0.2.0
    - grpcio==1.76.0
    - h11==0.16.0
    - h5py==3.14.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - idna==3.11
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - ipykernel==6.31.0
    - ipython==8.18.1
    - ipywidgets==8.1.8
    - isoduration==20.11.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.2
    - json5==0.12.1
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter==1.1.1
    - jupyter-client==8.6.3
    - jupyter-console==6.6.3
    - jupyter-core==5.8.1
    - jupyter-events==0.12.0
    - jupyter-lsp==2.3.0
    - jupyter-server==2.17.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.5.0
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.28.0
    - jupyterlab-widgets==3.0.16
    - keras==2.15.0
    - keras-tuner==1.4.8
    - kiwisolver==1.4.7
    - kt-legacy==1.0.5
    - lark==1.3.1
    - libclang==18.1.1
    - markdown==3.9
    - markdown-it-py==3.0.0
    - markupsafe==3.0.3
    - matplotlib==3.9.4
    - matplotlib-inline==0.2.1
    - mdurl==0.1.2
    - mistune==3.1.4
    - ml-dtypes==0.2.0
    - namex==0.1.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - notebook==7.5.0
    - notebook-shim==0.2.4
    - numpy==1.26.4
    - oauthlib==3.3.1
    - opt-einsum==3.4.0
    - overrides==7.7.0
    - packaging==25.0
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==11.3.0
    - platformdirs==4.4.0
    - prometheus-client==0.23.1
    - prompt-toolkit==3.0.52
    - protobuf==4.25.8
    - psutil==7.1.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pycparser==2.23
    - pygments==2.19.2
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - python-json-logger==4.0.0
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - referencing==0.36.2
    - regex==2025.11.3
    - requests==2.32.5
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rich==14.2.0
    - rpds-py==0.27.1
    - rsa==4.9.1
    - safetensors==0.7.0
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - send2trash==1.8.3
    - six==1.17.0
    - soupsieve==2.8
    - stack-data==0.6.3
    - tensorboard==2.15.2
    - tensorboard-data-server==0.7.2
    - tensorflow==2.15.0
    - tensorflow-estimator==2.15.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==3.1.0
    - terminado==0.18.1
    - threadpoolctl==3.6.0
    - tinycss2==1.4.0
    - tokenizers==0.22.1
    - tomli==2.3.0
    - tornado==6.5.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.57.3
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - uri-template==1.3.0
    - urllib3==2.6.0
    - wcwidth==0.2.14
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.9.0
    - werkzeug==3.1.4
    - widgetsnbextension==4.0.15
    - wrapt==1.14.2
    - zipp==3.23.0
prefix: /data1/ysq/anaconda3/envs/tensorflow2
